# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.154.0/containers/debian/.devcontainer/base.Dockerfile

ARG VARIANT="buster"
# FROM buildpack-deps:${VARIANT}-curl
FROM node:14.15.1-buster

RUN apt-get update -y && apt-get upgrade -y

